#!/bin/bash
# scripts/local/render-compose.sh
#
# Generates .run/docker-compose.yml for a K=N witness fleet.
# N is parameterised via the WITNESS_COUNT environment variable
# (default 1). Each witness becomes its own service bound to
# ${WITNESS_PORT_BASE}+i-1 on the host.
#
# Fixtures (witness PEM keys + network bootstrap doc) must
# already exist on the host under ./.run/ before `docker compose
# up` is run. `make dev-up` chains gen-fixtures → render-compose
# → docker compose so this is invisible in the happy path; on a
# raw invocation, run `make gen-fixtures` (or `go run
# ./cmd/gen-fixtures`) first.
#
# Usage:
#
#   WITNESS_COUNT=3 ./scripts/local/render-compose.sh
#   docker compose -f .run/docker-compose.yml up -d --build
#
# Wrapped by `make dev-up` for the common case.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RUN_DIR="${REPO_ROOT}/.run"
OUT_FILE="${RUN_DIR}/docker-compose.yml"

WITNESS_COUNT="${WITNESS_COUNT:-1}"
PORT_BASE="${WITNESS_PORT_BASE:-19001}"
MAX_WITNESSES="${WITNESS_MAX:-16}"

if ! [[ "${WITNESS_COUNT}" =~ ^[0-9]+$ ]] || [ "${WITNESS_COUNT}" -lt 1 ]; then
    echo "FATAL: WITNESS_COUNT must be a positive integer (got: ${WITNESS_COUNT})" >&2
    exit 2
fi
if [ "${WITNESS_COUNT}" -gt "${MAX_WITNESSES}" ]; then
    echo "FATAL: WITNESS_COUNT=${WITNESS_COUNT} exceeds WITNESS_MAX=${MAX_WITNESSES}." >&2
    echo "       raise WITNESS_MAX if you really need this many." >&2
    exit 2
fi
if ! [[ "${PORT_BASE}" =~ ^[0-9]+$ ]] || [ "${PORT_BASE}" -lt 1024 ] || [ "${PORT_BASE}" -gt 65000 ]; then
    echo "FATAL: WITNESS_PORT_BASE must be an unprivileged port (1024-65000, got: ${PORT_BASE})" >&2
    exit 2
fi

mkdir -p "${RUN_DIR}"

# Static preamble.
cat > "${OUT_FILE}" <<'PREAMBLE'
# .run/docker-compose.yml — GENERATED by scripts/local/render-compose.sh
#
# Do NOT edit this file by hand. Regenerate via:
#
#   WITNESS_COUNT=N ./scripts/local/render-compose.sh
#
# Fixtures (witness PEM keys + network bootstrap doc) under ./.run/
# must already exist before `docker compose up`. `make dev-up`
# chains gen-fixtures → render-compose → docker compose so the
# normal flow handles this.
#
# Build context is the repo root (one level up from .run/) so the
# Dockerfile at the module root resolves correctly.

services:
PREAMBLE

# Append each witness service.
for i in $(seq 1 "${WITNESS_COUNT}"); do
    port=$((PORT_BASE + i - 1))
    cat >> "${OUT_FILE}" <<SERVICE
  witness-${i}:
    build:
      context: ..
      dockerfile: Dockerfile
    image: standalone-witness:local
    container_name: standalone_witness_${i}
    command:
      - "-addr=:${port}"
      - "-key-file=/fixtures/witnesses/witness-${i}.pem"
      - "-bootstrap=/fixtures/network-bootstrap.json"
    ports:
      - "${port}:${port}"
    volumes:
      - ./:/fixtures:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:${port}/healthz | grep -q '^ok\$\$' || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
    restart: unless-stopped

SERVICE
done

echo "rendered ${OUT_FILE}  (witnesses=${WITNESS_COUNT}, ports :${PORT_BASE}..:$((PORT_BASE + WITNESS_COUNT - 1)))"
