#!/bin/bash
# scripts/local/write-env.sh
#
# Writes <run-dir>/witness.env — a sourceable / eval-able file that
# exports the LEDGER_* variables the ledger (cmd/ledger/config.go)
# reads to drive a real K-of-N quorum against this witness fleet:
#
#     LEDGER_WITNESS_ENDPOINTS
#     LEDGER_WITNESS_QUORUM_K
#     LEDGER_NETWORK_BOOTSTRAP_FILE
#
# Regenerated on every fleet boot (run-local.sh and `make dev-up`).
# Load it into your shell WITHOUT hand-typing the exports:
#
#     eval "$(make -s print-env)"      # or:  source .run/witness.env
#
# Usage: write-env.sh <count> <port-base> <bootstrap-file> <run-dir>
set -euo pipefail

COUNT="${1:?usage: write-env.sh <count> <port-base> <bootstrap-file> <run-dir>}"
PORT_BASE="${2:?port-base required}"
BOOTSTRAP_FILE="${3:?bootstrap-file required}"
RUN_DIR="${4:?run-dir required}"

# Absolute bootstrap path — a ledger started from another working
# directory must not receive a relative path.
case "${BOOTSTRAP_FILE}" in
    /*) ABS_BOOTSTRAP="${BOOTSTRAP_FILE}" ;;
    *)  ABS_BOOTSTRAP="$(cd "$(dirname "${BOOTSTRAP_FILE}")" && pwd)/$(basename "${BOOTSTRAP_FILE}")" ;;
esac

# Comma-separated endpoint list: localhost:PORT_BASE .. +COUNT-1.
ENDPOINTS=""
for i in $(seq 1 "${COUNT}"); do
    port=$((PORT_BASE + i - 1))
    ep="http://localhost:${port}"
    if [ -n "${ENDPOINTS}" ]; then ENDPOINTS="${ENDPOINTS},${ep}"; else ENDPOINTS="${ep}"; fi
done

ENV_FILE="${RUN_DIR}/witness.env"
mkdir -p "${RUN_DIR}"
cat > "${ENV_FILE}" <<EOF
# GENERATED by scripts/local/write-env.sh — regenerated on every fleet
# boot. Load into your shell with:
#     eval "\$(make -s print-env)"     # or:  source ${ENV_FILE}
export LEDGER_WITNESS_ENDPOINTS="${ENDPOINTS}"
export LEDGER_WITNESS_QUORUM_K="${COUNT}"
export LEDGER_NETWORK_BOOTSTRAP_FILE="${ABS_BOOTSTRAP}"
EOF

echo "== fleet env written: ${ENV_FILE} =="
echo "   load it (no manual exports):  eval \"\$(make -s print-env)\"   or:  source ${ENV_FILE}"
echo "   LEDGER_WITNESS_ENDPOINTS=${ENDPOINTS} (quorum_k=${COUNT})"
