/*
FILE PATH: store/rotation_archive.go

Witness-rotation evolution chain, reconstructed PG-free for the SDK seam (1.2b).

WHY the archive is the rotation INDEX, not the built chain:
bundle.StandaloneGather.FetchWitnessRotationChain(asOfTreeSize) returns elements
whose InclusionProof must satisfy witness.VerifyRotationInclusion AGAINST THE SHARED
anchor head — proof.TreeSize == asOfTreeSize, reconstructing to that head's RootHash
(witness/rotation_inclusion.go; log/bundle/v2_verify.go:427 proves each record's
position against the SHARED proof.CosignedHead, NOT the element's own head). RFC-6962
inclusion proofs are tree-size-specific, so a chain built at one size does NOT verify
at another. The only STABLE, archivable fact is therefore the set of rotation log
positions (effective_seqs); the per-anchor inclusion proofs are rebuilt at read time
from the SAME PG-free generators the read front already uses. (The SDK consults no
SMT leg for this chain — only record + inclusion — so no SMT proof is reconstructed.)

Additive + best-effort: a never-rotated network (index miss) yields the empty chain,
the SDK's "no rotations" result and the common case.
*/
package store

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/baseproof/baseproof/core/envelope"
	"github.com/baseproof/baseproof/log/bundle"
	"github.com/baseproof/baseproof/types"
)

// rotationArchiveVersion prefixes the index. v2: the archive is the seq INDEX (v1
// archived full elements, which is anchoring-incorrect — see the file header); a v1
// blob is rejected by decode and regenerated by the backfill job.
const rotationArchiveVersion byte = 2

// rotationChainKey is the LOGICAL object key for the archived rotation index — a
// single small key (rotations are rare). The *bytestore.S3 adapter prepends the
// per-log namespace. MUST match api/horizon.go rotationChainObject.
func rotationChainKey() string { return "witness-rotations" }

// encodeRotationIndex serializes the sorted rotation log positions: a 1-byte version
// then 8-byte big-endian seqs.
func encodeRotationIndex(seqs []uint64) []byte {
	out := make([]byte, 1+len(seqs)*8)
	out[0] = rotationArchiveVersion
	for i, s := range seqs {
		binary.BigEndian.PutUint64(out[1+i*8:], s)
	}
	return out
}

// decodeRotationIndex validates the version + framing and parses the seqs. A bad
// version or a body that is not a whole number of seqs is REJECTED — never silently
// treated as "no rotations".
func decodeRotationIndex(raw []byte) ([]uint64, error) {
	if len(raw) == 0 {
		return nil, fmt.Errorf("store/rotation-archive: empty index blob")
	}
	if raw[0] != rotationArchiveVersion {
		return nil, fmt.Errorf("store/rotation-archive: unsupported version %d (want %d)", raw[0], rotationArchiveVersion)
	}
	body := raw[1:]
	if len(body)%8 != 0 {
		return nil, fmt.Errorf("store/rotation-archive: corrupt index: %d body bytes not a multiple of 8", len(body))
	}
	seqs := make([]uint64, len(body)/8)
	for i := range seqs {
		seqs[i] = binary.BigEndian.Uint64(body[i*8:])
	}
	return seqs, nil
}

// RotationIndexReader reads the archived rotation-index blob from the object store.
// os.ErrNotExist when no rotation was ever archived (a never-rotated network).
type RotationIndexReader interface {
	ReadRotationIndex(ctx context.Context) ([]byte, error)
}

// RotationEntryBytesFetcher returns a rotation entry's canonical wire bytes by seq —
// PG-free (the byte store / entry tile). Same shape as the bundle gather's entry leg.
type RotationEntryBytesFetcher interface {
	FetchEntryBytes(ctx context.Context, seq uint64) ([]byte, time.Time, error)
}

// RotationInclusionFetcher builds an RFC-6962 inclusion proof for the leaf at seq in
// the tree of size treeSize — PG-free (tiles). Same shape as the bundle gather's
// inclusion leg; LeafHash may be zero on return (we bind it from the record bytes).
type RotationInclusionFetcher interface {
	FetchInclusionProof(ctx context.Context, seq, treeSize uint64) (*types.MerkleProof, error)
}

// ArchiveRotationChainFetcher satisfies bundle.StandaloneGather's
// FetchWitnessRotationChain PG-free: it reads the rotation index and rebuilds each
// element's inclusion proof AT the requested anchor, so every element verifies under
// witness.VerifyRotationInclusion against the shared anchor head.
type ArchiveRotationChainFetcher struct {
	index     RotationIndexReader
	entries   RotationEntryBytesFetcher
	inclusion RotationInclusionFetcher
	logDID    string
}

// NewArchiveRotationChainFetcher wires the fetcher to the index + the PG-free entry
// and inclusion generators (the read front's own).
func NewArchiveRotationChainFetcher(index RotationIndexReader, entries RotationEntryBytesFetcher, inclusion RotationInclusionFetcher, logDID string) *ArchiveRotationChainFetcher {
	return &ArchiveRotationChainFetcher{index: index, entries: entries, inclusion: inclusion, logDID: logDID}
}

// FetchWitnessRotationChain returns the witness-rotation evolution committed in the
// tree of size asOfTreeSize, each element {Record, InclusionProof} bound for
// witness.VerifyRotationInclusion against the anchor head: proof.TreeSize ==
// asOfTreeSize, LeafHash == OnLogEntryLeafHash(record), LeafPosition == seq. A
// rotation at seq >= asOfTreeSize is not yet a leaf in that tree and is excluded. A
// never-rotated network (index miss) yields the empty chain. (CommittingHead/SMTProof
// are left zero — the SDK's witness-chain replay consults neither; v2_verify.go:427.)
func (f *ArchiveRotationChainFetcher) FetchWitnessRotationChain(ctx context.Context, asOfTreeSize uint64) ([]bundle.RotationElement, error) {
	raw, err := f.index.ReadRotationIndex(ctx)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil // never rotated (or pre-archive) → empty chain
	}
	if err != nil {
		return nil, err
	}
	seqs, err := decodeRotationIndex(raw)
	if err != nil {
		return nil, err
	}
	var out []bundle.RotationElement
	for _, seq := range seqs {
		if seq >= asOfTreeSize {
			continue // not yet a leaf in the tree of size asOfTreeSize
		}
		record, _, fErr := f.entries.FetchEntryBytes(ctx, seq)
		if fErr != nil {
			return nil, fmt.Errorf("store/rotation-archive: entry seq=%d: %w", seq, fErr)
		}
		incl, iErr := f.inclusion.FetchInclusionProof(ctx, seq, asOfTreeSize)
		if iErr != nil {
			return nil, fmt.Errorf("store/rotation-archive: inclusion seq=%d @%d: %w", seq, asOfTreeSize, iErr)
		}
		if incl == nil {
			return nil, fmt.Errorf("store/rotation-archive: nil inclusion proof seq=%d", seq)
		}
		p := *incl
		// Bind the proof to THIS record + position — the witness.VerifyRotationInclusion
		// contract. The generator MAY return a zero LeafHash; populate it from the
		// record (envelope.OnLogEntryLeafHash), exactly as BuildBundle does.
		p.LeafHash = envelope.OnLogEntryLeafHash(record)
		if p.TreeSize != asOfTreeSize {
			return nil, fmt.Errorf("store/rotation-archive: seq=%d inclusion tree_size %d != anchor %d", seq, p.TreeSize, asOfTreeSize)
		}
		if p.LeafPosition != seq {
			return nil, fmt.Errorf("store/rotation-archive: seq=%d inclusion leaf_position %d != seq", seq, p.LeafPosition)
		}
		out = append(out, bundle.RotationElement{Record: record, InclusionProof: p})
	}
	return out, nil
}

// RotationIndexArchiveWriter durably archives the rotation index so the fetcher
// reconstructs the chain PG-free. Best-effort: the caller (rotation apply / backfill)
// logs a write error and never stalls on it.
type RotationIndexArchiveWriter struct {
	obj objectPutGetter
}

// NewRotationIndexArchiveWriter wires the writer to the object store. A nil obj makes
// ArchiveRotationIndex a no-op (the composition root can wire it unconditionally).
func NewRotationIndexArchiveWriter(obj objectPutGetter) *RotationIndexArchiveWriter {
	return &RotationIndexArchiveWriter{obj: obj}
}

// ArchiveRotationIndex writes the sorted rotation seqs to the single rotation key.
func (w *RotationIndexArchiveWriter) ArchiveRotationIndex(ctx context.Context, seqs []uint64) error {
	if w == nil || w.obj == nil {
		return nil
	}
	if err := w.obj.PutObject(ctx, rotationChainKey(), encodeRotationIndex(seqs)); err != nil {
		return fmt.Errorf("store/rotation-archive: put %s: %w", rotationChainKey(), err)
	}
	return nil
}
